name: athlyedge
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter_launcher_icons:
  adaptive_icon_background: "#27282A"
  adaptive_icon_foreground: "assets/images/launcher_foreground_icon.png"
  android: true
  image_path: "assets/images/launcher_icon.png"
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter_native_splash:
  android: true
  android_12:
    icon_background_color: "#27282A"
    icon_background_color_dark: "#27282A"
    image: assets/images/launcher_icon.png
    image_dark: assets/images/launcher_icon.png
  color: "#27282A"
  color_dark: "#27282A"
  image: assets/images/launcher_icon.png
  image_dark: assets/images/launcher_icon.png
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

